### ISSUE TITLE
Cursor is not properly reset on quit

### ISSUE THREAD

**Issue by lervag** [nvim-colortils/colortils.nvim#20]
I've started to test your plugin. It looks cool and useful; thanks!

I noticed that when I quit e.g. the picker, my cursor colors have been changed. It seems this is caused by the following code:

https://github.com/nvim-colortils/colortils.nvim/blob/6e2b200dfedd67d96eafd74b08adc08da95ccb4f/lua/colortils/tools/picker.lua#L562-L569

For some reason, you use `nvim_set_hl` to change the "Cursor" highlight group, but you do not revert it to the old setting. I believe that is a bug. IMHO, it is a severe bug, because it changes my environment after using your plugin in a way that is not acceptable to me.

I hope there is a simple fix for this. If I could immediately see how to fix it, I would propose a PR.

**Comment by lervag** [comment]
Looking a bit closer, it seems the problem is here:

https://github.com/nvim-colortils/colortils.nvim/blob/6e2b200dfedd67d96eafd74b08adc08da95ccb4f/lua/colortils/tools/picker.lua#L523-L529

Perhaps you meant to have lines 528 and 529 before line 523?

**Comment by max397574** [comment]
> Perhaps you meant to have lines 528 and 529 before line 523?

that's something I haven't seen thank you for that

I didn't realize that `Bold` isn't a default highlight group
I'll fix those things when I get home

**Comment by lervag** [comment]
No problem; thanks for the useful plugin!

**Comment by lervag** [comment]
Thanks!

**Comment by DasGandlaf** [comment]
I just installed the package, and I have this issue only when I use `replace_default_format`, or `set_register_default_format`. My Cursor goes black, and I cannot see it once I go back from the color picker.
