### ISSUE TITLE
Two changelogs break on MacOS

### ISSUE THREAD

**Issue by gregorias** [nvim-colortils/colortils.nvim#32]
MacOS uses a case-insensitive filesystem, and this repo having both `CHANGELOG.md`and `changelog.md` makes it impossible to work with it. Could you merge those files or something similar?

For more details, see https://learn.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity?view=azure-devops.

**Comment by danbee** [comment]
I've fixed this in a PR (#33) so hopefully the maintainer will merge it before releasing 1.2.0.

**Comment by danbee** [comment]
@gregorias I've merged the changelog fix into my own fork if you'd like to use that for now.
