### ISSUE TITLE
Does your plugin know how to colorize color codes in css files?

### ISSUE THREAD

**Issue by palandovalex** [nvim-colortils/colortils.nvim#35]
In your video, you can see that the color codes in the css file are colored, but it's not clear if it's your own plugin that can do this, or if it's the effect of another plugin.

**Comment by palandovalex** [comment]
In any case, when I output css palettes, the color codes are not colored, even when I output color gradients. It is unclear what is required for the plugin to work, I tested it on the "terminator" (TERM=xterm-256 and COLORTERM=truecolor), as well as in "kitty". It is displayed like this:

![Снимок экрана от 2024-03-06 11-54-17](https://github.com/nvim-colortils/colortils.nvim/assets/75374436/043aecb7-c0bd-4ec1-af41-8b8b8e461201)

![Снимок экрана от 2024-03-06 11-55-54](https://github.com/nvim-colortils/colortils.nvim/assets/75374436/cf4e480a-59e6-4b00-b07a-52e3ac3c3143)

**Comment by Debajyati** [comment]
I agree. I want to know how I can see the colorized hex codes.

**Comment by max397574** [comment]
use a plugin like colorizer.nvim or https://github.com/brenoprata10/nvim-highlight-colors

won't implement this for this plugin
